apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-module-ldifs
  labels:
    app: {{ template "ldap.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ppolicy.ldif: |-
    dn: cn=module,cn=config
    objectClass: olcModuleList
    cn: module
    olcModuleLoad: ppolicy.la

    dn: olcOverlay=ppolicy,olcDatabase={1}hdb,cn=config
    objectClass: olcOverlayConfig
    objectClass: olcPPolicyConfig
    olcOverlay: ppolicy
    olcPPolicyDefault: PPOLICY_DN
    olcPPolicyHashCleartext: FALSE
    olcPPolicyForwardUpdates: FALSE
    olcPPolicyUseLockout: FALSE
