apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-password-config
  labels:
    app: {{ template "ldap.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  checkpassword.conf: |-
    minPoints 4
    useCracklib 0
    minUpper 1
    minLower 6
    minDigit 1
    minPunct 1