{{- if eq .Values.global.jenkinsNamespace.create true }}
apiVersion: v1
kind: Namespace
metadata:
  name:
    jenkins-slaves-namespace
  annotations: 
    #"helm.sh/hook": "pre-upgrade"
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "1"
    #"helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    name: jenkins-slaves-namespace
    app: {{ template "jenkins.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}