{{- if and (eq .Values.global.jenkinsNamespace.create true) (eq .Values.Slave.enabled true) }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-slaves-role
  namespace: jenkins-slaves-namespace
  labels:
    app: {{ template "jenkins.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-jenkins-sa-binding
  namespace: jenkins-slaves-namespace
  annotations: 
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: {{ template "jenkins.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: jenkins-slaves-role
subjects:
- kind: ServiceAccount
  name: jenkins-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: {{ .Release.Namespace }}
  annotations: 
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "2"
    #"helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: {{ template "jenkins.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}