# Thie file sets up in-cluster service discovery for our app.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "jenkins.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "jenkins.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  # We want to listen on the default HTTP port, and send traffic to the port
  # our docker image is acutally listening on (which is defined in
  # deployment.yaml)
  - name: http
    port: {{ .Values.containerPort }}
    targetPort: http
  - name: jnlp
    port: 8443
    targetPort: 8443
  selector:
    app:  {{ .Chart.Name }}
