apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-properties
  labels:
    app: {{ template "ldap.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  LDAP_SERVER: {{ template "ldap.fullname" . }}
  LDAP_PORT: "389"
  LDAP_DOMAIN: "{{ .Values.image.env.SLAPD_DOMAIN }}"
  LDAP_ROOTDN: "{{ .Values.image.env.SLAPD_FULL_DOMAIN }}"
  LDAP_MANAGER_DN: "cn=admin,{{ .Values.image.env.SLAPD_FULL_DOMAIN }}"
  LDAP_DISPLAY_NAME_ATTRIBUTE_NAME: "displayName"
  LDAP_MAIL_ADDRESS_ATTRIBUTE_NAME: "mail"
  LDAP_USER_OBJECT_CLASS: "inetOrgPerson"
  LDAP_USER_ID_ATTRIBUTE_NAME: "uid"
  LDAP_GROUPMEMBER_ATRRIBUTE_NAME: "uniqueMember"
  LDAP_USER_BASE_DN: "ou=people"
  LDAP_GROUP_BASE_DN: "ou=groups"
  LDAP_USER_SEARCH: "uid={0}"
  LDAP_ACCOUNTPATTERN: "(cn=${username})"
  LDAP_ACCOUNTPATTERN_GERRIT: '(&(objectClass=inetOrgPerson)(uid=${username}))'
  LDAP_ACCOUNTFULLNAME: "${cn}"
  LDAP_GROUPPATTERN: "(cn=${groupname})"
  LDAP_GROUPOBJECT_CLASS: "groupOfUniqueNames"
  LDAP_GROUPPATTERN_GERRIT: '(&(objectClass=groupOfUniqueNames)(cn=${groupname}))'
  LDAP_GROUPMEMBERPATTERN: "(uniqueMember=${dn})"
  LDAP_GROUPMEMBERPATTERN_GERRIT: '(&(objectClass=groupOfUniqueNames)(uniqueMember=${dn}))'
  LDAP_GROUP_NAME_ADMIN: "administrators"