apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    app: {{ template "nginx.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/init/config-nginx.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: "init-config"
        image: "{{ .Values.Image.Name }}:{{ .Values.Image.Tag }}"
        imagePullPolicy: "{{ .Values.ImagePullPolicy }}"
        command: [ "sh", "/tmp/nginx/init.sh" ]
        envFrom:
        - configMapRef:
            name: ldap-properties
        env:
          - name: 'OPENLDAP_ROOT_PASSWORD'
            valueFrom:
              secretKeyRef:
                name: "ldap-secret"
                key: "ldap-password"
          - name: 'OPENLDAP_ROOT_USER'
            valueFrom:
              secretKeyRef:
                name: "ldap-secret"
                key: "ldap-manager-username"
        volumeMounts:
          - name: init
            mountPath: /tmp/nginx
          - name: nginx-home
            mountPath: /tmp/nginx-home
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf.template
            subPath: nginx.conf.template
            readOnly: true
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
            readOnly: true
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.Image.Name }}:{{ .Values.Image.Tag }}"
        livenessProbe:
          httpGet:
            path: /nginx-health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /nginx-health
            port: 8080
          initialDelaySeconds: 5
        ports:
          {{- range $key, $value := .Values.Image.containerPorts }}
          - name: {{ $key }}
            containerPort: {{ $value }}
          {{- end }}
        volumeMounts:
          - name: nginx-home
            mountPath: /etc/nginx
          - name: release-note
            mountPath: /usr/share/nginx/html/index.html
            subPath: index.html
            readOnly: true
          - name: release-note
            mountPath: /usr/share/nginx/html/50x.html
            subPath: 50x.html
            readOnly: true
          - name: release-note
            mountPath: /usr/share/nginx/html/plugins.json
            subPath: plugins.json
            readOnly: true
          - name: release-note
            mountPath: /usr/share/nginx/html/scss/style.scss
            subPath: style.scss
            readOnly: true
          - name: release-note
            mountPath: /usr/share/nginx/html/scss/_sizes.scss
            subPath: _sizes.scss
            readOnly: true
          - name: release-note
            mountPath: /usr/share/nginx/html/scss/_mixins.scss
            subPath: _mixins.scss
            readOnly: true
          - name: release-note
            mountPath: /usr/share/nginx/html/scss/_colors.scss
            subPath: _colors.scss
            readOnly: true
          - name: release-note
            mountPath: /usr/share/nginx/html/js/npm.js
            subPath: npm.js
            readOnly: true
          - name: release-note
            mountPath: /usr/share/nginx/html/js/appRN.js
            subPath: appRN.js
            readOnly: true
          - name: release-note
            mountPath: /usr/share/nginx/html/dir/component-list.html
            subPath: component-list.html
            readOnly: true
          - name: release-note
            mountPath: /usr/share/nginx/html/css/style.css
            subPath: style.css
            readOnly: true
          - name: release-note
            mountPath: /usr/share/nginx/html/css/style.css.map
            subPath: style.css.map
            readOnly: true
          - name: release-note
            mountPath: /usr/share/nginx/html/bp/blueprints-go-here
            subPath: blueprints-go-here
            readOnly: true
#################################################
################### IMAGES ######################
#################################################
          - name: release-note
            mountPath: /usr/share/nginx/html/img/jenkins.svg
            subPath: jenkins.svg
            readOnly: true
          - name: release-note
            mountPath: /usr/share/nginx/html/img/phpldapadmin.svg
            subPath: phpldapadmin.svg
            readOnly: true
          - name: release-note
            mountPath: /usr/share/nginx/html/img/sonarqube.svg
            subPath: sonarqube.svg
            readOnly: true
          - name: release-note
            mountPath: /usr/share/nginx/html/img/nexus.svg
            subPath: nexus.svg
            readOnly: true
      volumes:
        - name: nginx-home
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config
            defaultMode: 0766
        - name: init
          configMap:
            name: nginx-init
            defaultMode: 0755
        - name: release-note
          configMap:
            name: release-note
            defaultMode: 0755