# {{- if .Values.global.tools.gerrit.postgresql }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gerrit-postgresql
  annotations:
# {{- if (lookup "v1" "Secret" "" "{{ .Release.Name }}-gerrit-postgresql") }}
    "helm.sh/hook": pre-install
# {{- end }}
    # "helm.sh/hook": "pre-upgrade"
    # "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
  labels:
    app: {{ .Release.Name }}-gerrit-postgresql
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.gerritPostgresSecret.rootPassword }}
  root-password:  {{ .Values.gerritPostgresSecret.rootPassword | b64enc | quote }}
  {{- else }}
  root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.gerritPostgresSecret.rootUsername }}
  root-username:  {{ .Values.gerritPostgresSecret.rootUsername | b64enc | quote }}
  {{- else }}
  root-username: {{ printf "postgres" | b64enc | quote }}
  {{- end }}
  {{- if .Values.gerritPostgresSecret.rootDBName }}
  root-database:  {{ .Values.gerritPostgresSecret.rootDBName | b64enc | quote }}
  {{- else }}
  root-database: {{ printf "gerritdb" | b64enc | quote }}
  {{- end }}
# {{- end }}