
apiVersion: v1
kind: Secret
metadata:
  name: gerrit-mysql
  annotations:
    "helm.sh/hook": pre-install
    # "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
  labels:
    app: {{ .Release.Name }}-gerrit-mysql
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if  .Values.gerritmysql.mysqlRootPassword }}
  mysql-root-password:  {{  .Values.gerritmysql.mysqlRootPassword | b64enc | quote }}
  {{- else }}
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{ if  .Values.gerritmysql.mysqlPassword }}
  mysql-password:  {{  .Values.gerritmysql.mysqlPassword | b64enc | quote }}
  {{ else }}
  mysql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  mysql-user: {{  .Values.gerritmysql.mysqlUser | b64enc | quote }}
  mysql-database: {{  .Values.gerritmysql.mysqlDatabase | b64enc | quote }}
  mysql-port: {{  .Values.gerritmysql.service.port | b64enc | quote }}
{{- if .Values.global.tools.gerrit.enable }}
{{- if  .Values.gerritmysql.ssl.enabled }}
{{- if  .Values.gerritmysql.ssl.certificates }}
{{- range  .Values.gerritmysql.ssl.certificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    app: {{ .Release.Name }}-gerrit-mysql
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  ca.pem: {{ .ca | b64enc }}
  server-cert.pem: {{ .cert | b64enc }}
  server-key.pem: {{ .key | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
