# {{- if .Values.global.tools.sonarqube.postgresql }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sonarqube-postgresql
  annotations:
    "helm.sh/hook": pre-install
    # "helm.sh/hook": "pre-upgrade"
    # "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
  labels:
    app: {{ .Release.Name }}-sonarqbue-postgresql
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.sonarPostgresSecret.rootPassword }}
  root-password:  {{ .Values.sonarPostgresSecret.rootPassword | b64enc | quote }}
  {{- else }}
  root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.sonarPostgresSecret.rootUsername }}
  root-username:  {{ .Values.sonarPostgresSecret.rootUsername | b64enc | quote }}
  {{- else }}
  root-username: {{ printf "postgres" | b64enc | quote }}
  {{- end }}
  {{- if .Values.sonarPostgresSecret.rootDBName }}
  root-database:  {{ .Values.sonarPostgresSecret.rootDBName | b64enc | quote }}
  {{- else }}
  root-database: {{ printf "sonarqube" | b64enc | quote }}
  {{- end }}
# {{- end }}