
{{- if .Values.global.tools.sonarqube.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sonar-mysql
  annotations:
    "helm.sh/hook": pre-install
    # "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
  labels:
    app: {{ .Release.Name }}-sonar-mysql
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.sonarmysql.mysqlRootPassword }}
  mysql-root-password:  {{ .Values.sonarmysql.mysqlRootPassword | b64enc | quote }}
  {{- else }}
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{ if .Values.sonarmysql.mysqlPassword }}
  mysql-password:  {{ .Values.sonarmysql.mysqlPassword | b64enc | quote }}
  {{ else }}
  mysql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  mysql-user: {{ .Values.sonarmysql.mysqlUser | b64enc | quote }}
  mysql-database: {{ .Values.sonarmysql.mysqlDatabase | b64enc | quote }}
  mysql-port: {{ .Values.sonarmysql.service.port | b64enc | quote }}
{{- if .Values.global.tools.sonarqube.enable }}
  sonarqube-jdbc-url: {{ printf "jdbc:mysql://%s-sonarmysql:%s/%s?useUnicode=true&characterEncoding=utf8&useConfigs=maxPerformance" .Release.Name .Values.sonarmysql.service.port .Values.sonarmysql.mysqlDatabase | b64enc | quote }}
{{- if .Values.sonarmysql.ssl.enabled }}
{{- if .Values.sonarmysql.ssl.certificates }}
{{- range .Values.sonarmysql.ssl.certificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    app: {{ .Release.Name }}-sonar-mysql
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  ca.pem: {{ .ca | b64enc }}
  server-cert.pem: {{ .cert | b64enc }}
  server-key.pem: {{ .key | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}