---
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gerrit-etc-storage
  labels:
    app: {{ template "gerrit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
{{- if (eq "-" .Values.persistence.storageClass) }}
  #storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size.etc }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gerrit-git-storage
  labels:
    app: {{ template "gerrit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
{{- if (eq "-" .Values.persistence.storageClass) }}
  #storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size.git }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gerrit-db-storage
  labels:
    app: {{ template "gerrit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
{{- if (eq "-" .Values.persistence.storageClass) }}
  #storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size.db }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gerrit-cache-storage
  labels:
    app: {{ template "gerrit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
{{- if (eq "-" .Values.persistence.storageClass) }}
  #storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size.cache }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gerrit-index-storage
  labels:
    app: {{ template "gerrit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
{{- if (eq "-" .Values.persistence.storageClass) }}
  #storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size.index }}
{{- end }}