apiVersion: v1
kind: ConfigMap
metadata:
  name: gerrit-group-config
  labels:
    app: {{ template "gerrit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  upload-ssh-key-for-user.sh: |-
    export SSH_KEY=$( cat $1 | tr -d '\n' )
    export MEMBER=$2
    echo "Adding SSH Key $SSH_KEY to user $MEMBER"
    curl -X POST -H "Content-Type: text/plain" -u ${GERRIT_USERNAME}:${GERRIT_PASSWORD} -d "$SSH_KEY" "http://localhost:${GERRIT_HTTP_PORT}/gerrit/a/accounts/$2/sshkeys"

  add-to-group.sh: |-
    export GROUP=$1
    export MEMBER=$2
    echo "Adding Member $2 to group $1"
    curl -vvv -X PUT -u ${GERRIT_USERNAME}:${GERRIT_PASSWORD} http://localhost:${GERRIT_HTTP_PORT}/gerrit/a/groups/$1/groups/$2

  create-users-and-groups.sh: |-
    set +x
    
    until curl -sL -w "%{http_code}\\n" "http://localhost:${GERRIT_HTTP_PORT}/gerrit/login/%23/q/status:open" -o /dev/null | grep "401\|403" &> /dev/null
    do
        echo "Gerrit unavailable, sleeping for 10"
        sleep "10"
    done

    # Create the Administrative User
    ret=$(curl -X POST --data "username=${GERRIT_USERNAME}&password=${GERRIT_PASSWORD}" --write-out "%{http_code}" --silent --output /dev/null http://localhost:${GERRIT_HTTP_PORT}/gerrit/login/%23/q/status:open)
    echo "Created Admin User ${GERRIT_USERNAME} - Status $ret"

    ret=$(curl -X POST --data "username=${JENKINS_USERNAME}&password=${JENKINS_PASSWORD}" --write-out "%{http_code}" --silent --output /dev/null http://localhost:${GERRIT_HTTP_PORT}/gerrit/login/%23/q/status:open)
    echo "Created User ${JENKINS_USERNAME} - Status $ret"

    ## Create Developer and Reader Groups
    curl -vvv -X PUT -u "${GERRIT_USERNAME}:${GERRIT_PASSWORD}" http://localhost:${GERRIT_HTTP_PORT}/gerrit/a/groups/Developers
    curl -vvv -X PUT -u "${GERRIT_USERNAME}:${GERRIT_PASSWORD}" http://localhost:${GERRIT_HTTP_PORT}/gerrit/a/groups/Readers

    {{- range .Values.gerrit_roles.Administrators }}
      /tmp/gerrit-scripts/add-to-group.sh Administrators {{ . }}
    {{- end}}

    {{- range .Values.gerrit_roles.Developers }}
      /tmp/gerrit-scripts/add-to-group.sh Developers {{ . }}
    {{- end}}

    {{- if .Values.global.tools.jenkinsMaster.enable }}
      until [ -f /tmp/jenkins_public_keys/id_rsa.pub ]
      do
        echo "Waiting for Jenkins SSH Key to become available"
        sleep 10
      done

      /tmp/gerrit-scripts/upload-ssh-key-for-user.sh /tmp/jenkins_public_keys/id_rsa.pub jenkins
    {{- end }}