apiVersion: v1
kind: ConfigMap
metadata:
  name: gerrit-secure-config
  labels:
    app: {{ template "gerrit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  secure.config: |-
    [auth]
            registerEmailPrivateKey = 
    [database]
            password = 