apiVersion: v1
kind: ConfigMap
metadata:
  name: gerrit-config
  labels:
    app: {{ template "gerrit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  gerrit.config: |-
    [gerrit]
            basePath = git
            canonicalWebUrl = http://gerrit:8080/gerrit/
    [container]
            javaOptions = "-Dflogger.backend_factory=com.google.common.flogger.backend.log4j.Log4jBackendFactory#getInstance"
            javaOptions = "-Dflogger.logging_context=com.google.gerrit.server.logging.LoggingContext#getInstance"
            user = gerrit
            javaHome = /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre
    [index]
            type = lucene
    [auth]
            type = LDAP
            logoutUrl = http://gerrit:8080/gerrit/
            gitBasicAuth = true
            gitBasicAuthPolicy = HTTP_LDAP
    [receive]
            enableSignedPush = false
    [sendemail]
            smtpServer = localhost
            enable = false
    [sshd]
            listenAddress = *:29418
    [httpd]
            listenUrl = proxy-http://*:8080/gerrit/
    [cache]
            directory = cache
    [database]
            type = mysql
            hostname = gerrit-mysql
            port = 3306
            database = gerritdb
            username = gerrit
    [ldap]
            server = ldap://devtools-ldap
            username = cn=admin,ou=people,dc=ldap,dc=example,dc=org
            accountBase = ou=people,dc=ldap,dc=example,dc=org
            accountPattern = (&(objectClass=inetOrgPerson)(uid=${username}))
            accountFullname = ${cn}
            groupBase = ou=groups,dc=ldap,dc=example,dc=org
            groupPattern = (&(objectClass=groupOfUniqueNames)(cn=${groupname}))
            groupMemberPattern = (&(objectClass=groupOfUniqueNames)(uniqueMember=${dn}))
    [plugins]
            allowRemoteAdmin = true